### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by h-j-w** [unused/airstream#22]
I get this output
loading airstream blah.mp4 -o targetIP
=> press [q] to exit airstream
/var/lib/gems/1.9.1/gems/airstream-0.4.4/bin/airstream:105:in `at': can't convert nil into an exact number (TypeError)
	from /var/lib/gems/1.9.1/gems/airstream-0.4.4/bin/airstream:105:in `<top (required)>'
	from /usr/local/bin/airstream:23:in `load'
	from /usr/local/bin/airstream:23:in `<main>'

So looked at line 23

gem 'airstream', version
load Gem.bin_path('airstream', 'airstream', version)

Is this only grabbing version? Could I safely comment out?

**Comment by unused** [comment]
should be fixed with latest version

**Comment by MartijnDevNull** [comment]
Having this problem again

Latest version, Ubuntu Jessie, ruby 2.1.5p273
