### ISSUE TITLE
Streaming desktop (screen share) 

### ISSUE THREAD

**Issue by svalaskevicius** [unused/airstream#28]
Hi. 

Is it possible to use this app for streaming a screen capture stream e. G. From vlc or xvidcap? 

Thanks

**Comment by unused** [comment]
Hi
sorry for the late answer, I had not time to play around with it yet. As far as I see you cannot stream an unfinished file, therefore it fails with an error and I am not done with screen capture feature yet.

**Comment by dkniffin** [comment]
@unused Is screen share eventually going to be implemented?
