### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by risingbluefalcon** [unused/airstream#30]
The video streams for a second then stops. 
Link streams fine from an iOS device. 

$ airstream http://178.162.194.35:1935/mobile/stream2_320p/playlist.m3u8 -o 192.168.2.50
loading can take a few seconds...
=> press [q] to exit airstream
Progress |==========================================================================================================================================================| 100%
playlist 00:00:01 |=================================================================================================================================================| 100%
/var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/components/progressable.rb:82:in `validate_progress': You can't set the item's current value to be greater than the total. (RuntimeError)
	from /var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/components/progressable.rb:45:in `progress='
	from /var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:131:in `with_progressables'
	from /var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:48:in `block in progress='
	from /var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:147:in `with_update'
	from /var/lib/gems/1.9.1/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:48:in `progress='
	from /var/lib/gems/1.9.1/gems/airstream-0.4.7/bin/airstream:102:in `<top (required)>'
	from /usr/local/bin/airstream:23:in `load'
	from /usr/local/bin/airstream:23:in `<main>'

**Comment by unused** [comment]
I am afraid a playlist may not be supported by the protocol but resolved by iOS. That may be an easy and comfortable future feature - can you provide a sample of file you wanted to use? Feel free to send it via email.
