### ISSUE TITLE
Crash of the /*.mp3 file

### ISSUE THREAD

**Issue by HatsuMora** [unused/airstream#32]
Hello, i think that i found a issue, i use the airstream to play a folder /*.mp3 but several times it crash when the song it's playing and stop the 'playlist':

/var/lib/gems/2.1.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/components/progressable.rb:82:in `validate_progress': You can't set the item's current value to be greater than the total. (RuntimeError)
    from /var/lib/gems/2.1.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/components/progressable.rb:45:in`progress='
    from /var/lib/gems/2.1.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:131:in `with_progressables'
    from /var/lib/gems/2.1.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:48:in`block in progress='
    from /var/lib/gems/2.1.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:147:in `with_update'
    from /var/lib/gems/2.1.0/gems/ruby-progressbar-1.1.1/lib/progress_bar/base.rb:48:in`progress='
    from /var/lib/gems/2.1.0/gems/airstream-0.4.9/bin/airstream:102:in `<top (required)>'
    from /usr/local/bin/airstream:23:in`load'
    from /usr/local/bin/airstream:23:in `<main>'

ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
Ubuntu 14.10
airstream v0.4.9

**Comment by unused** [comment]
ref #8
